# Generated by Django 5.1.1 on 2024-09-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Estudiante_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
    ]
