# Generated by Django 5.1.1 on 2024-10-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0003_carrera_semestre_estudiante_carrera_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Carrera_id',
            new_name='Carrera',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Semestre_id',
            new_name='Semestre',
        ),
    ]
