# Generated by Django 5.1.1 on 2024-10-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0004_rename_carrera_id_estudiante_carrera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='Carrera',
            new_name='Carrera_id',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='Semestre',
            new_name='Semestre_id',
        ),
    ]
