# Generated by Django 5.1.1 on 2024-10-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0005_rename_carrera_estudiante_carrera_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='Carrera_id',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='Semestre_id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Carrera',
            field=models.ForeignKey(db_column='Carrera_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.carrera'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Semestre',
            field=models.ForeignKey(db_column='Semestre_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.semestre'),
        ),
    ]
