# Generated by Django 5.1.1 on 2024-10-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0006_remove_estudiante_carrera_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('Palabra', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'KeyWords',
            },
        ),
    ]
