# Generated by Django 5.1.1 on 2024-10-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0007_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalabraEstudiante',
            fields=[
                ('palabra_estudiante_id', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.estudiante')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Curso.keywords')),
            ],
            options={
                'db_table': 'Palabra_Estudiante ',
            },
        ),
    ]
