# Generated by Django 5.1.1 on 2024-10-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0008_palabraestudiante'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='palabraestudiante',
            table='Palabra_Estudiante',
        ),
    ]
