# Generated by Django 5.1.1 on 2024-10-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0009_alter_palabraestudiante_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEspecializacion',
            fields=[
                ('subesp_id', models.AutoField(primary_key=True, serialize=False)),
                ('colegio', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SubEspecializacion',
            },
        ),
    ]
