# Generated by Django 5.1.1 on 2024-10-12 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0010_subespecializacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subespecializacion',
            old_name='colegio',
            new_name='Colegio_id',
        ),
    ]
