# Generated by Django 5.1.1 on 2024-10-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0011_rename_colegio_subespecializacion_colegio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Subespecializacion',
            field=models.ForeignKey(db_column='SubEsp_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='Curso.subespecializacion'),
        ),
    ]
